name: dscim-epa
channels:
  - conda-forge
  - defaults
dependencies:
  - google-cloud-storage==2.5.0
  - statsmodels==0.13.2
  - python==3.8
  - pyfiglet==0.8.post1
  - pip
  - xarray
  - pandas
  - pandoc
  - numpy
  - scipy
  - jupyterlab
  - ipython
  - matplotlib
  - scipy
  - ipython
  - dask
  - pytest
  - pytest-cov
  - papermill
  - click
  - netcdf4
  - h5netcdf
  - zarr
  - cftime
  - bottleneck
  - nc-time-axis
  - jupyterlab_widgets
  - pip:
      - dscim==0.1.0
      - black==22.1.0
      - flake8
      - dill
      - numbagg
      - p_tqdm
      - impactlab_tools==0.4.0
      - inquirer==2.10.0
